# Generated by Django 5.1.6 on 2025-06-22 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Relatório',
                'verbose_name_plural': 'Categorias de Relatórios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_id', models.IntegerField(verbose_name='Local ID')),
                ('equipamento_id', models.IntegerField(verbose_name='Equipamento ID')),
                ('data_ocorrencia', models.DateTimeField(verbose_name='Data da Ocorrência')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridade')),
                ('progresso', models.IntegerField(default=0, verbose_name='Progresso (%)')),
                ('editavel', models.BooleanField(default=True, verbose_name='Editável')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tenant_id', models.IntegerField(default=1, verbose_name='Tenant ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'reports_report',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Frequência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('next_run', models.DateTimeField(verbose_name='Próxima Execução')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Agendamento de Relatório',
                'verbose_name_plural': 'Agendamentos de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nome do Campo')),
                ('field_value', models.TextField(verbose_name='Valor do Campo')),
                ('data_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('boolean', 'Booleano')], default='text', max_length=20, verbose_name='Tipo de Dado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Dado do Relatório',
                'verbose_name_plural': 'Dados dos Relatórios',
                'unique_together': {('report', 'field_name')},
            },
        ),
    ]
