# Generated by Django 5.1.6 on 2025-06-22 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='reports/anexos/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição da Imagem')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='reports.report', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Imagem do Relatório',
                'verbose_name_plural': 'Imagens dos Relatórios',
                'ordering': ['ordem', 'data_upload'],
            },
        ),
    ]
