# Generated by Django 5.1.6 on 2025-06-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_equipamento_options_remove_equipamento_marca_and_more'),
        ('reports', '0002_report_imagem_principal_alter_report_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='equipamento_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='local_id',
        ),
        migrations.AddField(
            model_name='report',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='report',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='locations.local', verbose_name='Local'),
        ),
    ]
