# Generated by Django 5.1.6 on 2025-06-22 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_equipamento_id_remove_report_local_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='atribuido_para',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável por executar este relatório', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído Para'),
        ),
        migrations.AlterField(
            model_name='report',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso_anterior', models.IntegerField(verbose_name='Progresso Anterior (%)')),
                ('progresso_novo', models.IntegerField(verbose_name='Novo Progresso (%)')),
                ('status_anterior', models.CharField(max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='Novo Status')),
                ('descricao_atualizacao', models.TextField(verbose_name='Descrição da Atualização')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='reports.report', verbose_name='Relatório')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Atualizou')),
            ],
            options={
                'verbose_name': 'Atualização de Relatório',
                'verbose_name_plural': 'Atualizações de Relatórios',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='ReportUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='reports/updates/', verbose_name='Imagem da Atualização')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição da Imagem')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='reports.reportupdate', verbose_name='Atualização')),
            ],
            options={
                'verbose_name': 'Imagem da Atualização',
                'verbose_name_plural': 'Imagens das Atualizações',
                'ordering': ['data_upload'],
            },
        ),
    ]
