# Generated by Django 5.1.6 on 2025-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o usuário está ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, default='', help_text='Nome completo do usuário', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='Hash da senha para compatibilidade', max_length=255, verbose_name='Password Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil_id',
            field=models.IntegerField(blank=True, help_text='ID do perfil/cargo do usuário', null=True, verbose_name='ID do Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(blank=True, default='', help_text='Hash da senha (não modificar diretamente)', max_length=255, verbose_name='Senha Hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='setor_id',
            field=models.IntegerField(blank=True, help_text='ID do setor de trabalho', null=True, verbose_name='ID do Setor'),
        ),
        migrations.AddField(
            model_name='user',
            name='unidade_id',
            field=models.IntegerField(blank=True, help_text='ID da unidade/departamento', null=True, verbose_name='ID da Unidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
