# Generated by Django 5.1.6 on 2025-06-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_ativo_user_nome_user_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('nivel_acesso', models.IntegerField(default=1, help_text='1=Baixo, 2=Médio, 3=Alto, 4=Total', verbose_name='Nível de Acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['nivel_acesso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('M_ELETRICA', 'M. Elétrica'), ('M_MECANICA', 'M. Mecânica'), ('REFRIGERACAO', 'Refrigeração'), ('PRODUCAO', 'Produção'), ('C_QUALIDADE', 'C. Qualidade'), ('TERCEIRO', 'Terceiro')], max_length=100, verbose_name='Nome do Setor')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil_id',
            field=models.IntegerField(blank=True, help_text='Campo de compatibilidade - use o campo "perfil_ref"', null=True, verbose_name='ID do Perfil (Legacy)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='setor_id',
            field=models.IntegerField(blank=True, help_text='Campo de compatibilidade - use o campo "setor_ref"', null=True, verbose_name='ID do Setor (Legacy)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidade_id',
            field=models.IntegerField(blank=True, help_text='Campo de compatibilidade - use o campo "unidade_ref"', null=True, verbose_name='ID da Unidade (Legacy)'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='authentication.perfil', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='setor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='authentication.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='setor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='authentication.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='unidade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='authentication.unidade', verbose_name='Unidade'),
        ),
    ]
