# Generated by Django 5.1.6 on 2025-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['nome'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='status',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Instalação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status_operacional',
            field=models.CharField(choices=[('operando', 'Operando'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='operando', max_length=20, verbose_name='Status Operacional'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tenant_id',
            field=models.IntegerField(default=1, verbose_name='Tenant ID'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('computador', 'Computador'), ('impressora', 'Impressora'), ('servidor', 'Servidor'), ('roteador', 'Roteador'), ('switch', 'Switch'), ('telefone', 'Telefone'), ('monitor', 'Monitor'), ('projetor', 'Projetor'), ('scanner', 'Scanner'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='local',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('escritorio', 'Escritório'), ('fabrica', 'Fábrica'), ('deposito', 'Depósito'), ('loja', 'Loja'), ('filial', 'Filial'), ('matriz', 'Matriz'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
