# Generated by Django 5.1.6 on 2025-06-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_equipamento_options_remove_equipamento_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status_operacional',
            field=models.CharField(choices=[('operando', 'Operando'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo'), ('almoxarifado', 'Almoxarifado')], default='operando', max_length=20, verbose_name='Status Operacional'),
        ),
    ]
