# Generated by Django 4.2.7 on 2025-06-22 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_alter_equipamento_status_operacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Motor')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('monofasico', 'Monofásico'), ('trifasico', 'Trifásico'), ('cc', 'Corrente Contínua'), ('servo', 'Servo Motor'), ('passo', 'Motor de Passo'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('potencia', models.DecimalField(decimal_places=2, help_text='Potência em cavalos-vapor (CV)', max_digits=10, verbose_name='Potência (CV)')),
                ('voltagem', models.DecimalField(decimal_places=2, help_text='Tensão nominal em Volts', max_digits=10, verbose_name='Voltagem (V)')),
                ('corrente', models.DecimalField(decimal_places=2, help_text='Corrente nominal em Ampères', max_digits=10, verbose_name='Corrente (A)')),
                ('rpm', models.IntegerField(help_text='Rotações por minuto', verbose_name='RPM')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('status_operacional', models.CharField(choices=[('operando', 'Operando'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='operando', max_length=20, verbose_name='Status Operacional')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motores', to='locations.local', verbose_name='Local de Instalação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
                'ordering': ['nome'],
            },
        ),
    ]
