# Generated by Django 4.2.7 on 2025-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='status_operacional',
            field=models.CharField(choices=[('operando', 'Operando'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo'), ('almoxarifado', 'Almoxarifado')], default='operando', max_length=20, verbose_name='Status Operacional'),
        ),
    ]
